### PR TITLE
Upgrade/python 3.6 – Fix to_markdown

### PR DESCRIPTION
**Pull request by dwickwire**
Right now the [to_markdown](https://github.com/Crossway/antimarkdown/blob/9031eb21f360c7314e63efd6b5644ee57782bde8/antimarkdown/__init__.py#L12-L15) method is completely broken and relies on the handlers which currently do nothing, so I've removed them here.  

Note, I'm not sure what markdown-highlight did, but we removed it from GitHub during our retreat, so I'm going to assume its not related to the problem.

In order to try and address the to_markdown method's brokenness I've tried rectifying the existing code, but it just doesn't seem to do anything in terms of converting to markdown.  Its quite puzzling how it ever worked.

In order to try and find some solution I experimented with [pypandoc](https://pypi.python.org/pypi/pypandoc) which does handle html-to-markdown conversions quite nicely, for instance:

```python
In [1]: from pypandoc import convert_text

In [2]: html = '<p>AT&amp;T has an ampersand in their name.</p>\n<p>This &amp; that.</p>\n<p>4 &lt; 5.</p>\n<p>6 &gt; 5.</p>\n<p>Here\'s a <a h
   ...: ref="http://example.com/?foo=1&amp;bar=2">link</a> with an ampersand in the URL.</p>\n<p>Here\'s a link with an amersand in the link te
   ...: xt: <a href="http://att.com/" title="AT&amp;T">AT&amp;T</a>.</p>\n<p>Here\'s an inline <a href="/script?foo=1&amp;bar=2">link</a>.</p>\
   ...: n'

In [3]: convert_text(html, 'md', format='html')
Out[3]: 'AT&T has an ampersand in their name.\n\nThis & that.\n\n4 &lt; 5.\n\n6 &gt; 5.\n\nHere\'s a [link](http://example.com/?foo=1&bar=2) with an ampersand in\nthe URL.\n\nHere\'s a link with an amersand in the link text:\n[AT&T](http://att.com/ "AT&T").\n\nHere\'s an inline [link](/script?foo=1&bar=2).\n'
```

#### Rendered Markdown:
AT&T has an ampersand in their name.

This & that.

4 &lt; 5.

6 &gt; 5.

Here\'s a [link](http://example.com/?foo=1&bar=2) with an ampersand in
the URL.

Here\'s a link with an amersand in the link text:
[AT&T](http://att.com/ "AT&T").

Here\'s an inline [link](/script?foo=1&bar=2).

------

Pandoc is a really nice library, I've used it routinely to convert my markdown papers into latex for report submission at school.  

The problem we have is that pandoc/pypandoc relies on *reasonably* formatted HTML andor markdown in order to be consistent.  The [html2markdown feature tests](https://github.com/Crossway/antimarkdown/blob/9031eb21f360c7314e63efd6b5644ee57782bde8/features/html2markdown.feature) are testing many uncommon cases and thus the html to markdown conversion fails.  

Aside from not handling markdown conversion the same as how it was previously handled, it also seems to handle a few cases incorrectly.  

Some of the most common differences I noticed were the following:
- parses list items with a `-` instead of `*`, non-issue but requires the tests to change.
- parses html p tags into new lines but not div tags, instead of one, so  `<div><p></p></div>` becomes `'<div>\n\n</div>\n'`  This is different than how things are currently handled but its just a style difference, I say its a non-issue.

Issues I see which we would need to address, were we to continue forward with pypandoc are:
- we might have to switch to using pypandoc for the markdown to html too, but it also parses markdown to html differently from the existing structures we have, this needs to be investigated further.
- it handled a few conversions rather oddly: (e.g. `<p><br /></p>` becomes `\`)

@eykd At this point I'd like to leave this branch in your hands.  This was your repository and I've done more than I hoped already in terms of refactoring this repository.  This repo was holding up requirement installations in skyhook because of BeautifulSoup.

### CODE REVIEW

**Comment by dwickwire** [comment]
I will also add, it seems a lot of the areas where pypandoc didn't perform as well were mostly for really poorly formatted HTML.  I personally think we should try and bend over backwards to try and support those cases.

A great example of what I mean: 
- [angle-links-and-img.html](https://github.com/Crossway/antimarkdown/blob/master/features/steps/data/basic/angle-links-and-img.html)

```html
<p><a href="simple link" title="title">link</a>
<img alt="image" src="http://example.com/image.jpg" />
<a href="http://example.com/(()((())923)(">link</a>
<img alt="image" src="link(()))(" /></p>
```
- [angle-links-and-img.txt](https://github.com/Crossway/antimarkdown/blob/master/features/steps/data/basic/angle-links-and-img.txt)

```markdown
[link](<simple link> "title") ![image](<http://example.com/image.jpg>) [link](<http://example.com/\(\(\)\(\(\(\)\)923\)\(>) ![image](<link\(\(\)\)\)\(>)
```

It handles this *reasonably* alright, but it doesn't match the existing tests.

**Comment by dwickwire** [comment]
Having said ALL that – if you want to take a stab at bringing back the `handler.render` function we can do that too.  It seems like something in python 3 handles the deque or stack differently.

Basically the deque keeps coming back empty.

we can chat about this more in the meeting too

**Comment by dwickwire** [comment]
Per meeting, @eykd will take a stab at restoring the `handler.render` and `handler.build_render_tree` used from `to_markdown`.

**Comment by eykd** [comment]
Closing in favor of #8.

**Pull request closed without merging**
