### PR TITLE
Better list style

### PR DESCRIPTION
**Pull request by eykd**
- Move LI style to a common variable.
- Change LI style from `*` to `-`
- Break link between space after LI marker and indentation
  - Only one space after the list marker
  - Indented list items are indented four spaces, in keeping with python-markdown's prejudices.

### CODE REVIEW

**Comment by eykd** [comment]
So, the output will now look like this:

```
- [Overview](<#overview>)
    - [Philosophy](<#philosophy>)
    - [Inline HTML](<#html>)
    - [Automatic Escaping for Special Characters](<#autoescape>)
- [Block Elements](<#block>)
```

Instead of:

```
*   [Overview](<#overview>)
    *   [Philosophy](<#philosophy>)
    *   [Inline HTML](<#html>)
    *   [Automatic Escaping for Special Characters](<#autoescape>)
*   [Block Elements](<#block>)
```

Unfortunately, python-markdown does not support this:

```
- [Overview](<#overview>)
  - [Philosophy](<#philosophy>)
  - [Inline HTML](<#html>)
  - [Automatic Escaping for Special Characters](<#autoescape>)
-   [Block Elements](<#block>)
```

Python-markdown does not recognize those as nested list items, even though Markdown.pl, CommonMark, and any other Markdown renderer you care to think of does.

**Comment by StephenLJohnson** [comment]
I would prefer to allow two space indents, but if we can't then four is ok.

**Comment by eykd** [comment]
So would I, but I can't find a markdown implementation for python that
supports plugins, which we need to support some of our unfortunate WYSIWYG
editor features.

Speaking of the WYSIWYG editor, I should make sure we support all of its
output. :S

**Comment by adamzap** [comment]
Which features do we need plugin support for?

**Comment by eykd** [comment]
We have a plugin to support colored background spans. I also noticed today that I need to add support for colored text. I think I must have done the initial work for this before we started using Redactor--I don't remember there being colored text, or so many color options available.

I've been playing around with the Redactor editor on esvbible.org, and I'm disheartened by the HTML it outputs. I'm looking to see if there aren't some ways to clean it up a bit. I hope I haven't been leading us down a primrose path.

**Comment by adamzap** [comment]
Gotcha.

I don't mean to nag about this, but maybe we can export the my-notes tables and see how many people are actually using the coloring features?

**Comment by eykd** [comment]
I've avoided doing it because it's a lot of work for dubious gain. We're talking about analyzing over a million blobs of HTML. I'm already pretty sure that if there's an edit control, a significant fraction of people will use it.

That being said, I think I'm going to do it, as I want some live test data to check all this apparatus against.

**Comment by eykd** [comment]
So, out of 745k accounts on ESVBible.org, 73k have at least one note.

Out of those 73k accounts, 9k of them have used at least one `span` tag. 

Those 9k users, however, have used 397k span tags, with a median usage of 4 spans. 

There appear to be some very heavy users of spans, but the numbers don't look right, so I'm going to write them off as weird bots until I can figure out how to look at them more closely. But even when I write off the top 100 users of spans, there's still an average of ~17, potentially quite a few heavy span users.

Note: I'm not differentiating between background color and text color at this point.

**Comment by adamzap** [comment]
So they only reason a span tag could be there is text color or background color?

**Comment by eykd** [comment]
Without examining all 397k span tags, I'm going to guess "yes", since the only attributes we allow are `href`, `src`, and `style`.

**Comment by adamzap** [comment]
Can you get what percent of notes uses text color or background color?

**Comment by dwickwire** [comment]
Should we add the WIP label to this?

**Comment by eykd** [comment]
This isn't going to happen any time soon, if ever, due to by-design limitations in python-markdown.

**Pull request closed without merging**
